# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

from argo_workflows.api_client import ApiClient
from argo_workflows.api.cluster_workflow_template_service_api_endpoints.create_cluster_workflow_template import CreateClusterWorkflowTemplate
from argo_workflows.api.cluster_workflow_template_service_api_endpoints.delete_cluster_workflow_template import DeleteClusterWorkflowTemplate
from argo_workflows.api.cluster_workflow_template_service_api_endpoints.get_cluster_workflow_template import GetClusterWorkflowTemplate
from argo_workflows.api.cluster_workflow_template_service_api_endpoints.lint_cluster_workflow_template import LintClusterWorkflowTemplate
from argo_workflows.api.cluster_workflow_template_service_api_endpoints.list_cluster_workflow_templates import ListClusterWorkflowTemplates
from argo_workflows.api.cluster_workflow_template_service_api_endpoints.update_cluster_workflow_template import UpdateClusterWorkflowTemplate


class ClusterWorkflowTemplateServiceApi(
    CreateClusterWorkflowTemplate,
    DeleteClusterWorkflowTemplate,
    GetClusterWorkflowTemplate,
    LintClusterWorkflowTemplate,
    ListClusterWorkflowTemplates,
    UpdateClusterWorkflowTemplate,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
