# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

from argo_workflows.api_client import ApiClient
from argo_workflows.api.cron_workflow_service_api_endpoints.create_cron_workflow import CreateCronWorkflow
from argo_workflows.api.cron_workflow_service_api_endpoints.delete_cron_workflow import DeleteCronWorkflow
from argo_workflows.api.cron_workflow_service_api_endpoints.get_cron_workflow import GetCronWorkflow
from argo_workflows.api.cron_workflow_service_api_endpoints.lint_cron_workflow import LintCronWorkflow
from argo_workflows.api.cron_workflow_service_api_endpoints.list_cron_workflows import ListCronWorkflows
from argo_workflows.api.cron_workflow_service_api_endpoints.resume_cron_workflow import ResumeCronWorkflow
from argo_workflows.api.cron_workflow_service_api_endpoints.suspend_cron_workflow import SuspendCronWorkflow
from argo_workflows.api.cron_workflow_service_api_endpoints.update_cron_workflow import UpdateCronWorkflow


class CronWorkflowServiceApi(
    CreateCronWorkflow,
    DeleteCronWorkflow,
    GetCronWorkflow,
    LintCronWorkflow,
    ListCronWorkflows,
    ResumeCronWorkflow,
    SuspendCronWorkflow,
    UpdateCronWorkflow,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
