# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

from argo_workflows.api_client import ApiClient
from argo_workflows.api.event_service_api_endpoints.list_workflow_event_bindings import ListWorkflowEventBindings
from argo_workflows.api.event_service_api_endpoints.receive_event import ReceiveEvent


class EventServiceApi(
    ListWorkflowEventBindings,
    ReceiveEvent,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
