# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

from argo_workflows.api_client import ApiClient
from argo_workflows.api.event_source_service_api_endpoints.create_event_source import CreateEventSource
from argo_workflows.api.event_source_service_api_endpoints.delete_event_source import DeleteEventSource
from argo_workflows.api.event_source_service_api_endpoints.event_sources_logs import EventSourcesLogs
from argo_workflows.api.event_source_service_api_endpoints.get_event_source import GetEventSource
from argo_workflows.api.event_source_service_api_endpoints.list_event_sources import ListEventSources
from argo_workflows.api.event_source_service_api_endpoints.update_event_source import UpdateEventSource
from argo_workflows.api.event_source_service_api_endpoints.watch_event_sources import WatchEventSources


class EventSourceServiceApi(
    CreateEventSource,
    DeleteEventSource,
    EventSourcesLogs,
    GetEventSource,
    ListEventSources,
    UpdateEventSource,
    WatchEventSources,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
