# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

from argo_workflows.api_client import ApiClient
from argo_workflows.api.pipeline_service_api_endpoints.delete_pipeline import DeletePipeline
from argo_workflows.api.pipeline_service_api_endpoints.get_pipeline import GetPipeline
from argo_workflows.api.pipeline_service_api_endpoints.list_pipelines import ListPipelines
from argo_workflows.api.pipeline_service_api_endpoints.pipeline_logs import PipelineLogs
from argo_workflows.api.pipeline_service_api_endpoints.restart_pipeline import RestartPipeline
from argo_workflows.api.pipeline_service_api_endpoints.watch_pipelines import WatchPipelines
from argo_workflows.api.pipeline_service_api_endpoints.watch_steps import WatchSteps


class PipelineServiceApi(
    DeletePipeline,
    GetPipeline,
    ListPipelines,
    PipelineLogs,
    RestartPipeline,
    WatchPipelines,
    WatchSteps,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
