# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

from argo_workflows.api_client import ApiClient
from argo_workflows.api.sensor_service_api_endpoints.create_sensor import CreateSensor
from argo_workflows.api.sensor_service_api_endpoints.delete_sensor import DeleteSensor
from argo_workflows.api.sensor_service_api_endpoints.get_sensor import GetSensor
from argo_workflows.api.sensor_service_api_endpoints.list_sensors import ListSensors
from argo_workflows.api.sensor_service_api_endpoints.sensors_logs import SensorsLogs
from argo_workflows.api.sensor_service_api_endpoints.update_sensor import UpdateSensor
from argo_workflows.api.sensor_service_api_endpoints.watch_sensors import WatchSensors


class SensorServiceApi(
    CreateSensor,
    DeleteSensor,
    GetSensor,
    ListSensors,
    SensorsLogs,
    UpdateSensor,
    WatchSensors,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
