# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

from argo_workflows.api_client import ApiClient
from argo_workflows.api.workflow_template_service_api_endpoints.create_workflow_template import CreateWorkflowTemplate
from argo_workflows.api.workflow_template_service_api_endpoints.delete_workflow_template import DeleteWorkflowTemplate
from argo_workflows.api.workflow_template_service_api_endpoints.get_workflow_template import GetWorkflowTemplate
from argo_workflows.api.workflow_template_service_api_endpoints.lint_workflow_template import LintWorkflowTemplate
from argo_workflows.api.workflow_template_service_api_endpoints.list_workflow_templates import ListWorkflowTemplates
from argo_workflows.api.workflow_template_service_api_endpoints.update_workflow_template import UpdateWorkflowTemplate


class WorkflowTemplateServiceApi(
    CreateWorkflowTemplate,
    DeleteWorkflowTemplate,
    GetWorkflowTemplate,
    LintWorkflowTemplate,
    ListWorkflowTemplates,
    UpdateWorkflowTemplate,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
