# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class CephFSVolumeSource(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Represents a Ceph Filesystem mount that lasts the lifetime of a pod Cephfs volumes do not support ownership management or SELinux relabeling.
    """
    _required_property_names = set((
        'monitors',
    ))
    
    
    class monitors(
        ListSchema
    ):
        _items = StrSchema
    path = StrSchema
    readOnly = BoolSchema
    secretFile = StrSchema

    @classmethod
    @property
    def secretRef(cls) -> typing.Type['LocalObjectReference']:
        return LocalObjectReference
    user = StrSchema


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        monitors: monitors,
        path: typing.Union[path, Unset] = unset,
        readOnly: typing.Union[readOnly, Unset] = unset,
        secretFile: typing.Union[secretFile, Unset] = unset,
        secretRef: typing.Union['LocalObjectReference', Unset] = unset,
        user: typing.Union[user, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'CephFSVolumeSource':
        return super().__new__(
            cls,
            *args,
            monitors=monitors,
            path=path,
            readOnly=readOnly,
            secretFile=secretFile,
            secretRef=secretRef,
            user=user,
            _configuration=_configuration,
            **kwargs,
        )

from argo_workflows.model.local_object_reference import LocalObjectReference
