# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class CSIVolumeSource(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Represents a source location of a volume to mount, managed by an external CSI driver
    """
    _required_property_names = set((
        'driver',
    ))
    driver = StrSchema
    fsType = StrSchema

    @classmethod
    @property
    def nodePublishSecretRef(cls) -> typing.Type['LocalObjectReference']:
        return LocalObjectReference
    readOnly = BoolSchema
    
    
    class volumeAttributes(
        DictSchema
    ):
        _additional_properties = StrSchema
    
    
        def __new__(
            cls,
            *args: typing.Union[dict, frozendict, ],
            _configuration: typing.Optional[Configuration] = None,
            **kwargs: typing.Type[Schema],
        ) -> 'volumeAttributes':
            return super().__new__(
                cls,
                *args,
                _configuration=_configuration,
                **kwargs,
            )


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        driver: driver,
        fsType: typing.Union[fsType, Unset] = unset,
        nodePublishSecretRef: typing.Union['LocalObjectReference', Unset] = unset,
        readOnly: typing.Union[readOnly, Unset] = unset,
        volumeAttributes: typing.Union[volumeAttributes, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'CSIVolumeSource':
        return super().__new__(
            cls,
            *args,
            driver=driver,
            fsType=fsType,
            nodePublishSecretRef=nodePublishSecretRef,
            readOnly=readOnly,
            volumeAttributes=volumeAttributes,
            _configuration=_configuration,
            **kwargs,
        )

from argo_workflows.model.local_object_reference import LocalObjectReference
