# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class EnvFromSource(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    EnvFromSource represents the source of a set of ConfigMaps
    """

    @classmethod
    @property
    def configMapRef(cls) -> typing.Type['ConfigMapEnvSource']:
        return ConfigMapEnvSource
    prefix = StrSchema

    @classmethod
    @property
    def secretRef(cls) -> typing.Type['SecretEnvSource']:
        return SecretEnvSource


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        configMapRef: typing.Union['ConfigMapEnvSource', Unset] = unset,
        prefix: typing.Union[prefix, Unset] = unset,
        secretRef: typing.Union['SecretEnvSource', Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'EnvFromSource':
        return super().__new__(
            cls,
            *args,
            configMapRef=configMapRef,
            prefix=prefix,
            secretRef=secretRef,
            _configuration=_configuration,
            **kwargs,
        )

from argo_workflows.model.config_map_env_source import ConfigMapEnvSource
from argo_workflows.model.secret_env_source import SecretEnvSource
