# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class GithubComArgoprojLabsArgoDataflowApiV1alpha1S3(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    bucket = StrSchema

    @classmethod
    @property
    def credentials(cls) -> typing.Type['GithubComArgoprojLabsArgoDataflowApiV1alpha1AWSCredentials']:
        return GithubComArgoprojLabsArgoDataflowApiV1alpha1AWSCredentials

    @classmethod
    @property
    def endpoint(cls) -> typing.Type['GithubComArgoprojLabsArgoDataflowApiV1alpha1AWSEndpoint']:
        return GithubComArgoprojLabsArgoDataflowApiV1alpha1AWSEndpoint
    name = StrSchema
    region = StrSchema


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        bucket: typing.Union[bucket, Unset] = unset,
        credentials: typing.Union['GithubComArgoprojLabsArgoDataflowApiV1alpha1AWSCredentials', Unset] = unset,
        endpoint: typing.Union['GithubComArgoprojLabsArgoDataflowApiV1alpha1AWSEndpoint', Unset] = unset,
        name: typing.Union[name, Unset] = unset,
        region: typing.Union[region, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'GithubComArgoprojLabsArgoDataflowApiV1alpha1S3':
        return super().__new__(
            cls,
            *args,
            bucket=bucket,
            credentials=credentials,
            endpoint=endpoint,
            name=name,
            region=region,
            _configuration=_configuration,
            **kwargs,
        )

from argo_workflows.model.github_com_argoproj_labs_argo_dataflow_api_v1alpha1_aws_credentials import GithubComArgoprojLabsArgoDataflowApiV1alpha1AWSCredentials
from argo_workflows.model.github_com_argoproj_labs_argo_dataflow_api_v1alpha1_aws_endpoint import GithubComArgoprojLabsArgoDataflowApiV1alpha1AWSEndpoint
