# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class GithubComArgoprojLabsArgoDataflowApiV1alpha1Git(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    branch = StrSchema
    
    
    class command(
        ListSchema
    ):
        _items = StrSchema
    
    
    class env(
        ListSchema
    ):
    
        @classmethod
        @property
        def _items(cls) -> typing.Type['EnvVar']:
            return EnvVar
    image = StrSchema
    insecureIgnoreHostKey = BoolSchema

    @classmethod
    @property
    def passwordSecret(cls) -> typing.Type['SecretKeySelector']:
        return SecretKeySelector
    path = StrSchema

    @classmethod
    @property
    def sshPrivateKeySecret(cls) -> typing.Type['SecretKeySelector']:
        return SecretKeySelector
    url = StrSchema

    @classmethod
    @property
    def usernameSecret(cls) -> typing.Type['SecretKeySelector']:
        return SecretKeySelector


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        branch: typing.Union[branch, Unset] = unset,
        command: typing.Union[command, Unset] = unset,
        env: typing.Union[env, Unset] = unset,
        image: typing.Union[image, Unset] = unset,
        insecureIgnoreHostKey: typing.Union[insecureIgnoreHostKey, Unset] = unset,
        passwordSecret: typing.Union['SecretKeySelector', Unset] = unset,
        path: typing.Union[path, Unset] = unset,
        sshPrivateKeySecret: typing.Union['SecretKeySelector', Unset] = unset,
        url: typing.Union[url, Unset] = unset,
        usernameSecret: typing.Union['SecretKeySelector', Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'GithubComArgoprojLabsArgoDataflowApiV1alpha1Git':
        return super().__new__(
            cls,
            *args,
            branch=branch,
            command=command,
            env=env,
            image=image,
            insecureIgnoreHostKey=insecureIgnoreHostKey,
            passwordSecret=passwordSecret,
            path=path,
            sshPrivateKeySecret=sshPrivateKeySecret,
            url=url,
            usernameSecret=usernameSecret,
            _configuration=_configuration,
            **kwargs,
        )

from argo_workflows.model.env_var import EnvVar
from argo_workflows.model.secret_key_selector import SecretKeySelector
