# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class GithubComArgoprojLabsArgoDataflowApiV1alpha1KafkaSink(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    acks = StrSchema
    _async = BoolSchema
    locals()['async'] = _async
    del locals()['_async']
    batchSize = StrSchema
    compressionType = StrSchema
    enableIdempotence = BoolSchema

    @classmethod
    @property
    def kafka(cls) -> typing.Type['GithubComArgoprojLabsArgoDataflowApiV1alpha1Kafka']:
        return GithubComArgoprojLabsArgoDataflowApiV1alpha1Kafka

    @classmethod
    @property
    def linger(cls) -> typing.Type['Duration']:
        return Duration
    maxInflight = IntSchema

    @classmethod
    @property
    def messageTimeout(cls) -> typing.Type['Duration']:
        return Duration


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        acks: typing.Union[acks, Unset] = unset,
        batchSize: typing.Union[batchSize, Unset] = unset,
        compressionType: typing.Union[compressionType, Unset] = unset,
        enableIdempotence: typing.Union[enableIdempotence, Unset] = unset,
        kafka: typing.Union['GithubComArgoprojLabsArgoDataflowApiV1alpha1Kafka', Unset] = unset,
        linger: typing.Union['Duration', Unset] = unset,
        maxInflight: typing.Union[maxInflight, Unset] = unset,
        messageTimeout: typing.Union['Duration', Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'GithubComArgoprojLabsArgoDataflowApiV1alpha1KafkaSink':
        return super().__new__(
            cls,
            *args,
            acks=acks,
            batchSize=batchSize,
            compressionType=compressionType,
            enableIdempotence=enableIdempotence,
            kafka=kafka,
            linger=linger,
            maxInflight=maxInflight,
            messageTimeout=messageTimeout,
            _configuration=_configuration,
            **kwargs,
        )

from argo_workflows.model.duration import Duration
from argo_workflows.model.github_com_argoproj_labs_argo_dataflow_api_v1alpha1_kafka import GithubComArgoprojLabsArgoDataflowApiV1alpha1Kafka
