# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class GithubComArgoprojLabsArgoDataflowApiV1alpha1S3Source(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    concurrency = IntSchema

    @classmethod
    @property
    def pollPeriod(cls) -> typing.Type['Duration']:
        return Duration

    @classmethod
    @property
    def s3(cls) -> typing.Type['GithubComArgoprojLabsArgoDataflowApiV1alpha1S3']:
        return GithubComArgoprojLabsArgoDataflowApiV1alpha1S3


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        concurrency: typing.Union[concurrency, Unset] = unset,
        pollPeriod: typing.Union['Duration', Unset] = unset,
        s3: typing.Union['GithubComArgoprojLabsArgoDataflowApiV1alpha1S3', Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'GithubComArgoprojLabsArgoDataflowApiV1alpha1S3Source':
        return super().__new__(
            cls,
            *args,
            concurrency=concurrency,
            pollPeriod=pollPeriod,
            s3=s3,
            _configuration=_configuration,
            **kwargs,
        )

from argo_workflows.model.duration import Duration
from argo_workflows.model.github_com_argoproj_labs_argo_dataflow_api_v1alpha1_s3 import GithubComArgoprojLabsArgoDataflowApiV1alpha1S3
