# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class IoArgoprojEventsV1alpha1KafkaTrigger(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    KafkaTrigger refers to the specification of the Kafka trigger.
    """
    compress = BoolSchema
    flushFrequency = IntSchema
    
    
    class parameters(
        ListSchema
    ):
    
        @classmethod
        @property
        def _items(cls) -> typing.Type['IoArgoprojEventsV1alpha1TriggerParameter']:
            return IoArgoprojEventsV1alpha1TriggerParameter
    partition = IntSchema
    partitioningKey = StrSchema
    
    
    class payload(
        ListSchema
    ):
    
        @classmethod
        @property
        def _items(cls) -> typing.Type['IoArgoprojEventsV1alpha1TriggerParameter']:
            return IoArgoprojEventsV1alpha1TriggerParameter
    requiredAcks = IntSchema

    @classmethod
    @property
    def sasl(cls) -> typing.Type['IoArgoprojEventsV1alpha1SASLConfig']:
        return IoArgoprojEventsV1alpha1SASLConfig

    @classmethod
    @property
    def tls(cls) -> typing.Type['IoArgoprojEventsV1alpha1TLSConfig']:
        return IoArgoprojEventsV1alpha1TLSConfig
    topic = StrSchema
    url = StrSchema
    version = StrSchema


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        compress: typing.Union[compress, Unset] = unset,
        flushFrequency: typing.Union[flushFrequency, Unset] = unset,
        parameters: typing.Union[parameters, Unset] = unset,
        partition: typing.Union[partition, Unset] = unset,
        partitioningKey: typing.Union[partitioningKey, Unset] = unset,
        payload: typing.Union[payload, Unset] = unset,
        requiredAcks: typing.Union[requiredAcks, Unset] = unset,
        sasl: typing.Union['IoArgoprojEventsV1alpha1SASLConfig', Unset] = unset,
        tls: typing.Union['IoArgoprojEventsV1alpha1TLSConfig', Unset] = unset,
        topic: typing.Union[topic, Unset] = unset,
        url: typing.Union[url, Unset] = unset,
        version: typing.Union[version, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'IoArgoprojEventsV1alpha1KafkaTrigger':
        return super().__new__(
            cls,
            *args,
            compress=compress,
            flushFrequency=flushFrequency,
            parameters=parameters,
            partition=partition,
            partitioningKey=partitioningKey,
            payload=payload,
            requiredAcks=requiredAcks,
            sasl=sasl,
            tls=tls,
            topic=topic,
            url=url,
            version=version,
            _configuration=_configuration,
            **kwargs,
        )

from argo_workflows.model.io_argoproj_events_v1alpha1_sasl_config import IoArgoprojEventsV1alpha1SASLConfig
from argo_workflows.model.io_argoproj_events_v1alpha1_tls_config import IoArgoprojEventsV1alpha1TLSConfig
from argo_workflows.model.io_argoproj_events_v1alpha1_trigger_parameter import IoArgoprojEventsV1alpha1TriggerParameter
