# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class IoArgoprojWorkflowV1alpha1SubmitOpts(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    SubmitOpts are workflow submission options
    """
    annotations = StrSchema
    dryRun = BoolSchema
    entryPoint = StrSchema
    generateName = StrSchema
    labels = StrSchema
    name = StrSchema

    @classmethod
    @property
    def ownerReference(cls) -> typing.Type['OwnerReference']:
        return OwnerReference
    
    
    class parameters(
        ListSchema
    ):
        _items = StrSchema
    podPriorityClassName = StrSchema
    priority = IntSchema
    serverDryRun = BoolSchema
    serviceAccount = StrSchema


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        annotations: typing.Union[annotations, Unset] = unset,
        dryRun: typing.Union[dryRun, Unset] = unset,
        entryPoint: typing.Union[entryPoint, Unset] = unset,
        generateName: typing.Union[generateName, Unset] = unset,
        labels: typing.Union[labels, Unset] = unset,
        name: typing.Union[name, Unset] = unset,
        ownerReference: typing.Union['OwnerReference', Unset] = unset,
        parameters: typing.Union[parameters, Unset] = unset,
        podPriorityClassName: typing.Union[podPriorityClassName, Unset] = unset,
        priority: typing.Union[priority, Unset] = unset,
        serverDryRun: typing.Union[serverDryRun, Unset] = unset,
        serviceAccount: typing.Union[serviceAccount, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'IoArgoprojWorkflowV1alpha1SubmitOpts':
        return super().__new__(
            cls,
            *args,
            annotations=annotations,
            dryRun=dryRun,
            entryPoint=entryPoint,
            generateName=generateName,
            labels=labels,
            name=name,
            ownerReference=ownerReference,
            parameters=parameters,
            podPriorityClassName=podPriorityClassName,
            priority=priority,
            serverDryRun=serverDryRun,
            serviceAccount=serviceAccount,
            _configuration=_configuration,
            **kwargs,
        )

from argo_workflows.model.owner_reference import OwnerReference
