# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class IoArgoprojWorkflowV1alpha1GitArtifact(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    GitArtifact is the location of an git artifact
    """
    _required_property_names = set((
        'repo',
    ))
    branch = StrSchema
    depth = IntSchema
    disableSubmodules = BoolSchema
    
    
    class fetch(
        ListSchema
    ):
        _items = StrSchema
    insecureIgnoreHostKey = BoolSchema

    @classmethod
    @property
    def passwordSecret(cls) -> typing.Type['SecretKeySelector']:
        return SecretKeySelector
    repo = StrSchema
    revision = StrSchema
    singleBranch = BoolSchema

    @classmethod
    @property
    def sshPrivateKeySecret(cls) -> typing.Type['SecretKeySelector']:
        return SecretKeySelector

    @classmethod
    @property
    def usernameSecret(cls) -> typing.Type['SecretKeySelector']:
        return SecretKeySelector


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        repo: repo,
        branch: typing.Union[branch, Unset] = unset,
        depth: typing.Union[depth, Unset] = unset,
        disableSubmodules: typing.Union[disableSubmodules, Unset] = unset,
        fetch: typing.Union[fetch, Unset] = unset,
        insecureIgnoreHostKey: typing.Union[insecureIgnoreHostKey, Unset] = unset,
        passwordSecret: typing.Union['SecretKeySelector', Unset] = unset,
        revision: typing.Union[revision, Unset] = unset,
        singleBranch: typing.Union[singleBranch, Unset] = unset,
        sshPrivateKeySecret: typing.Union['SecretKeySelector', Unset] = unset,
        usernameSecret: typing.Union['SecretKeySelector', Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'IoArgoprojWorkflowV1alpha1GitArtifact':
        return super().__new__(
            cls,
            *args,
            repo=repo,
            branch=branch,
            depth=depth,
            disableSubmodules=disableSubmodules,
            fetch=fetch,
            insecureIgnoreHostKey=insecureIgnoreHostKey,
            passwordSecret=passwordSecret,
            revision=revision,
            singleBranch=singleBranch,
            sshPrivateKeySecret=sshPrivateKeySecret,
            usernameSecret=usernameSecret,
            _configuration=_configuration,
            **kwargs,
        )

from argo_workflows.model.secret_key_selector import SecretKeySelector
