# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class IoArgoprojEventsV1alpha1SensorSpec(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    
    
    class dependencies(
        ListSchema
    ):
    
        @classmethod
        @property
        def _items(cls) -> typing.Type['IoArgoprojEventsV1alpha1EventDependency']:
            return IoArgoprojEventsV1alpha1EventDependency
    errorOnFailedRound = BoolSchema
    eventBusName = StrSchema
    replicas = IntSchema

    @classmethod
    @property
    def template(cls) -> typing.Type['IoArgoprojEventsV1alpha1Template']:
        return IoArgoprojEventsV1alpha1Template
    
    
    class triggers(
        ListSchema
    ):
    
        @classmethod
        @property
        def _items(cls) -> typing.Type['IoArgoprojEventsV1alpha1Trigger']:
            return IoArgoprojEventsV1alpha1Trigger


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        dependencies: typing.Union[dependencies, Unset] = unset,
        errorOnFailedRound: typing.Union[errorOnFailedRound, Unset] = unset,
        eventBusName: typing.Union[eventBusName, Unset] = unset,
        replicas: typing.Union[replicas, Unset] = unset,
        template: typing.Union['IoArgoprojEventsV1alpha1Template', Unset] = unset,
        triggers: typing.Union[triggers, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'IoArgoprojEventsV1alpha1SensorSpec':
        return super().__new__(
            cls,
            *args,
            dependencies=dependencies,
            errorOnFailedRound=errorOnFailedRound,
            eventBusName=eventBusName,
            replicas=replicas,
            template=template,
            triggers=triggers,
            _configuration=_configuration,
            **kwargs,
        )

from argo_workflows.model.io_argoproj_events_v1alpha1_event_dependency import IoArgoprojEventsV1alpha1EventDependency
from argo_workflows.model.io_argoproj_events_v1alpha1_template import IoArgoprojEventsV1alpha1Template
from argo_workflows.model.io_argoproj_events_v1alpha1_trigger import IoArgoprojEventsV1alpha1Trigger
