# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class IoArgoprojWorkflowV1alpha1OSSArtifact(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    OSSArtifact is the location of an Alibaba Cloud OSS artifact
    """
    _required_property_names = set((
        'key',
    ))

    @classmethod
    @property
    def accessKeySecret(cls) -> typing.Type['SecretKeySelector']:
        return SecretKeySelector
    bucket = StrSchema
    createBucketIfNotPresent = BoolSchema
    endpoint = StrSchema
    key = StrSchema

    @classmethod
    @property
    def lifecycleRule(cls) -> typing.Type['IoArgoprojWorkflowV1alpha1OSSLifecycleRule']:
        return IoArgoprojWorkflowV1alpha1OSSLifecycleRule

    @classmethod
    @property
    def secretKeySecret(cls) -> typing.Type['SecretKeySelector']:
        return SecretKeySelector
    securityToken = StrSchema


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        key: key,
        accessKeySecret: typing.Union['SecretKeySelector', Unset] = unset,
        bucket: typing.Union[bucket, Unset] = unset,
        createBucketIfNotPresent: typing.Union[createBucketIfNotPresent, Unset] = unset,
        endpoint: typing.Union[endpoint, Unset] = unset,
        lifecycleRule: typing.Union['IoArgoprojWorkflowV1alpha1OSSLifecycleRule', Unset] = unset,
        secretKeySecret: typing.Union['SecretKeySelector', Unset] = unset,
        securityToken: typing.Union[securityToken, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'IoArgoprojWorkflowV1alpha1OSSArtifact':
        return super().__new__(
            cls,
            *args,
            key=key,
            accessKeySecret=accessKeySecret,
            bucket=bucket,
            createBucketIfNotPresent=createBucketIfNotPresent,
            endpoint=endpoint,
            lifecycleRule=lifecycleRule,
            secretKeySecret=secretKeySecret,
            securityToken=securityToken,
            _configuration=_configuration,
            **kwargs,
        )

from argo_workflows.model.io_argoproj_workflow_v1alpha1_oss_lifecycle_rule import IoArgoprojWorkflowV1alpha1OSSLifecycleRule
from argo_workflows.model.secret_key_selector import SecretKeySelector
