# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class IoArgoprojWorkflowV1alpha1HTTPAuth(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    @classmethod
    @property
    def basicAuth(cls) -> typing.Type['IoArgoprojWorkflowV1alpha1BasicAuth']:
        return IoArgoprojWorkflowV1alpha1BasicAuth

    @classmethod
    @property
    def clientCert(cls) -> typing.Type['IoArgoprojWorkflowV1alpha1ClientCertAuth']:
        return IoArgoprojWorkflowV1alpha1ClientCertAuth

    @classmethod
    @property
    def oauth2(cls) -> typing.Type['IoArgoprojWorkflowV1alpha1OAuth2Auth']:
        return IoArgoprojWorkflowV1alpha1OAuth2Auth


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        basicAuth: typing.Union['IoArgoprojWorkflowV1alpha1BasicAuth', Unset] = unset,
        clientCert: typing.Union['IoArgoprojWorkflowV1alpha1ClientCertAuth', Unset] = unset,
        oauth2: typing.Union['IoArgoprojWorkflowV1alpha1OAuth2Auth', Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'IoArgoprojWorkflowV1alpha1HTTPAuth':
        return super().__new__(
            cls,
            *args,
            basicAuth=basicAuth,
            clientCert=clientCert,
            oauth2=oauth2,
            _configuration=_configuration,
            **kwargs,
        )

from argo_workflows.model.io_argoproj_workflow_v1alpha1_basic_auth import IoArgoprojWorkflowV1alpha1BasicAuth
from argo_workflows.model.io_argoproj_workflow_v1alpha1_client_cert_auth import IoArgoprojWorkflowV1alpha1ClientCertAuth
from argo_workflows.model.io_argoproj_workflow_v1alpha1_o_auth2_auth import IoArgoprojWorkflowV1alpha1OAuth2Auth
