# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class IoArgoprojWorkflowV1alpha1S3ArtifactRepository(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    S3ArtifactRepository defines the controller configuration for an S3 artifact repository
    """

    @classmethod
    @property
    def accessKeySecret(cls) -> typing.Type['SecretKeySelector']:
        return SecretKeySelector
    bucket = StrSchema

    @classmethod
    @property
    def createBucketIfNotPresent(cls) -> typing.Type['IoArgoprojWorkflowV1alpha1CreateS3BucketOptions']:
        return IoArgoprojWorkflowV1alpha1CreateS3BucketOptions

    @classmethod
    @property
    def encryptionOptions(cls) -> typing.Type['IoArgoprojWorkflowV1alpha1S3EncryptionOptions']:
        return IoArgoprojWorkflowV1alpha1S3EncryptionOptions
    endpoint = StrSchema
    insecure = BoolSchema
    keyFormat = StrSchema
    keyPrefix = StrSchema
    region = StrSchema
    roleARN = StrSchema

    @classmethod
    @property
    def secretKeySecret(cls) -> typing.Type['SecretKeySelector']:
        return SecretKeySelector
    useSDKCreds = BoolSchema


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        accessKeySecret: typing.Union['SecretKeySelector', Unset] = unset,
        bucket: typing.Union[bucket, Unset] = unset,
        createBucketIfNotPresent: typing.Union['IoArgoprojWorkflowV1alpha1CreateS3BucketOptions', Unset] = unset,
        encryptionOptions: typing.Union['IoArgoprojWorkflowV1alpha1S3EncryptionOptions', Unset] = unset,
        endpoint: typing.Union[endpoint, Unset] = unset,
        insecure: typing.Union[insecure, Unset] = unset,
        keyFormat: typing.Union[keyFormat, Unset] = unset,
        keyPrefix: typing.Union[keyPrefix, Unset] = unset,
        region: typing.Union[region, Unset] = unset,
        roleARN: typing.Union[roleARN, Unset] = unset,
        secretKeySecret: typing.Union['SecretKeySelector', Unset] = unset,
        useSDKCreds: typing.Union[useSDKCreds, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'IoArgoprojWorkflowV1alpha1S3ArtifactRepository':
        return super().__new__(
            cls,
            *args,
            accessKeySecret=accessKeySecret,
            bucket=bucket,
            createBucketIfNotPresent=createBucketIfNotPresent,
            encryptionOptions=encryptionOptions,
            endpoint=endpoint,
            insecure=insecure,
            keyFormat=keyFormat,
            keyPrefix=keyPrefix,
            region=region,
            roleARN=roleARN,
            secretKeySecret=secretKeySecret,
            useSDKCreds=useSDKCreds,
            _configuration=_configuration,
            **kwargs,
        )

from argo_workflows.model.io_argoproj_workflow_v1alpha1_create_s3_bucket_options import IoArgoprojWorkflowV1alpha1CreateS3BucketOptions
from argo_workflows.model.io_argoproj_workflow_v1alpha1_s3_encryption_options import IoArgoprojWorkflowV1alpha1S3EncryptionOptions
from argo_workflows.model.secret_key_selector import SecretKeySelector
