# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class IoArgoprojWorkflowV1alpha1ArtifactRepository(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    ArtifactRepository represents an artifact repository in which a controller will store its artifacts
    """
    archiveLogs = BoolSchema

    @classmethod
    @property
    def artifactory(cls) -> typing.Type['IoArgoprojWorkflowV1alpha1ArtifactoryArtifactRepository']:
        return IoArgoprojWorkflowV1alpha1ArtifactoryArtifactRepository

    @classmethod
    @property
    def gcs(cls) -> typing.Type['IoArgoprojWorkflowV1alpha1GCSArtifactRepository']:
        return IoArgoprojWorkflowV1alpha1GCSArtifactRepository

    @classmethod
    @property
    def hdfs(cls) -> typing.Type['IoArgoprojWorkflowV1alpha1HDFSArtifactRepository']:
        return IoArgoprojWorkflowV1alpha1HDFSArtifactRepository

    @classmethod
    @property
    def oss(cls) -> typing.Type['IoArgoprojWorkflowV1alpha1OSSArtifactRepository']:
        return IoArgoprojWorkflowV1alpha1OSSArtifactRepository

    @classmethod
    @property
    def s3(cls) -> typing.Type['IoArgoprojWorkflowV1alpha1S3ArtifactRepository']:
        return IoArgoprojWorkflowV1alpha1S3ArtifactRepository


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        archiveLogs: typing.Union[archiveLogs, Unset] = unset,
        artifactory: typing.Union['IoArgoprojWorkflowV1alpha1ArtifactoryArtifactRepository', Unset] = unset,
        gcs: typing.Union['IoArgoprojWorkflowV1alpha1GCSArtifactRepository', Unset] = unset,
        hdfs: typing.Union['IoArgoprojWorkflowV1alpha1HDFSArtifactRepository', Unset] = unset,
        oss: typing.Union['IoArgoprojWorkflowV1alpha1OSSArtifactRepository', Unset] = unset,
        s3: typing.Union['IoArgoprojWorkflowV1alpha1S3ArtifactRepository', Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'IoArgoprojWorkflowV1alpha1ArtifactRepository':
        return super().__new__(
            cls,
            *args,
            archiveLogs=archiveLogs,
            artifactory=artifactory,
            gcs=gcs,
            hdfs=hdfs,
            oss=oss,
            s3=s3,
            _configuration=_configuration,
            **kwargs,
        )

from argo_workflows.model.io_argoproj_workflow_v1alpha1_artifactory_artifact_repository import IoArgoprojWorkflowV1alpha1ArtifactoryArtifactRepository
from argo_workflows.model.io_argoproj_workflow_v1alpha1_gcs_artifact_repository import IoArgoprojWorkflowV1alpha1GCSArtifactRepository
from argo_workflows.model.io_argoproj_workflow_v1alpha1_hdfs_artifact_repository import IoArgoprojWorkflowV1alpha1HDFSArtifactRepository
from argo_workflows.model.io_argoproj_workflow_v1alpha1_oss_artifact_repository import IoArgoprojWorkflowV1alpha1OSSArtifactRepository
from argo_workflows.model.io_argoproj_workflow_v1alpha1_s3_artifact_repository import IoArgoprojWorkflowV1alpha1S3ArtifactRepository
