# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class IoArgoprojEventsV1alpha1EventDependency(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    eventName = StrSchema
    eventSourceName = StrSchema

    @classmethod
    @property
    def filters(cls) -> typing.Type['IoArgoprojEventsV1alpha1EventDependencyFilter']:
        return IoArgoprojEventsV1alpha1EventDependencyFilter
    filtersLogicalOperator = StrSchema
    name = StrSchema

    @classmethod
    @property
    def transform(cls) -> typing.Type['IoArgoprojEventsV1alpha1EventDependencyTransformer']:
        return IoArgoprojEventsV1alpha1EventDependencyTransformer


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        eventName: typing.Union[eventName, Unset] = unset,
        eventSourceName: typing.Union[eventSourceName, Unset] = unset,
        filters: typing.Union['IoArgoprojEventsV1alpha1EventDependencyFilter', Unset] = unset,
        filtersLogicalOperator: typing.Union[filtersLogicalOperator, Unset] = unset,
        name: typing.Union[name, Unset] = unset,
        transform: typing.Union['IoArgoprojEventsV1alpha1EventDependencyTransformer', Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'IoArgoprojEventsV1alpha1EventDependency':
        return super().__new__(
            cls,
            *args,
            eventName=eventName,
            eventSourceName=eventSourceName,
            filters=filters,
            filtersLogicalOperator=filtersLogicalOperator,
            name=name,
            transform=transform,
            _configuration=_configuration,
            **kwargs,
        )

from argo_workflows.model.io_argoproj_events_v1alpha1_event_dependency_filter import IoArgoprojEventsV1alpha1EventDependencyFilter
from argo_workflows.model.io_argoproj_events_v1alpha1_event_dependency_transformer import IoArgoprojEventsV1alpha1EventDependencyTransformer
