# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class IoArgoprojEventsV1alpha1SNSEventSource(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    @classmethod
    @property
    def accessKey(cls) -> typing.Type['SecretKeySelector']:
        return SecretKeySelector

    @classmethod
    @property
    def filter(cls) -> typing.Type['IoArgoprojEventsV1alpha1EventSourceFilter']:
        return IoArgoprojEventsV1alpha1EventSourceFilter
    
    
    class metadata(
        DictSchema
    ):
        _additional_properties = StrSchema
    
    
        def __new__(
            cls,
            *args: typing.Union[dict, frozendict, ],
            _configuration: typing.Optional[Configuration] = None,
            **kwargs: typing.Type[Schema],
        ) -> 'metadata':
            return super().__new__(
                cls,
                *args,
                _configuration=_configuration,
                **kwargs,
            )
    region = StrSchema
    roleARN = StrSchema

    @classmethod
    @property
    def secretKey(cls) -> typing.Type['SecretKeySelector']:
        return SecretKeySelector
    topicArn = StrSchema
    validateSignature = BoolSchema

    @classmethod
    @property
    def webhook(cls) -> typing.Type['IoArgoprojEventsV1alpha1WebhookContext']:
        return IoArgoprojEventsV1alpha1WebhookContext


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        accessKey: typing.Union['SecretKeySelector', Unset] = unset,
        filter: typing.Union['IoArgoprojEventsV1alpha1EventSourceFilter', Unset] = unset,
        metadata: typing.Union[metadata, Unset] = unset,
        region: typing.Union[region, Unset] = unset,
        roleARN: typing.Union[roleARN, Unset] = unset,
        secretKey: typing.Union['SecretKeySelector', Unset] = unset,
        topicArn: typing.Union[topicArn, Unset] = unset,
        validateSignature: typing.Union[validateSignature, Unset] = unset,
        webhook: typing.Union['IoArgoprojEventsV1alpha1WebhookContext', Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'IoArgoprojEventsV1alpha1SNSEventSource':
        return super().__new__(
            cls,
            *args,
            accessKey=accessKey,
            filter=filter,
            metadata=metadata,
            region=region,
            roleARN=roleARN,
            secretKey=secretKey,
            topicArn=topicArn,
            validateSignature=validateSignature,
            webhook=webhook,
            _configuration=_configuration,
            **kwargs,
        )

from argo_workflows.model.io_argoproj_events_v1alpha1_event_source_filter import IoArgoprojEventsV1alpha1EventSourceFilter
from argo_workflows.model.io_argoproj_events_v1alpha1_webhook_context import IoArgoprojEventsV1alpha1WebhookContext
from argo_workflows.model.secret_key_selector import SecretKeySelector
