# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class IoArgoprojEventsV1alpha1S3Artifact(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    @classmethod
    @property
    def accessKey(cls) -> typing.Type['SecretKeySelector']:
        return SecretKeySelector

    @classmethod
    @property
    def bucket(cls) -> typing.Type['IoArgoprojEventsV1alpha1S3Bucket']:
        return IoArgoprojEventsV1alpha1S3Bucket
    endpoint = StrSchema
    
    
    class events(
        ListSchema
    ):
        _items = StrSchema

    @classmethod
    @property
    def filter(cls) -> typing.Type['IoArgoprojEventsV1alpha1S3Filter']:
        return IoArgoprojEventsV1alpha1S3Filter
    insecure = BoolSchema
    
    
    class metadata(
        DictSchema
    ):
        _additional_properties = StrSchema
    
    
        def __new__(
            cls,
            *args: typing.Union[dict, frozendict, ],
            _configuration: typing.Optional[Configuration] = None,
            **kwargs: typing.Type[Schema],
        ) -> 'metadata':
            return super().__new__(
                cls,
                *args,
                _configuration=_configuration,
                **kwargs,
            )
    region = StrSchema

    @classmethod
    @property
    def secretKey(cls) -> typing.Type['SecretKeySelector']:
        return SecretKeySelector


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        accessKey: typing.Union['SecretKeySelector', Unset] = unset,
        bucket: typing.Union['IoArgoprojEventsV1alpha1S3Bucket', Unset] = unset,
        endpoint: typing.Union[endpoint, Unset] = unset,
        events: typing.Union[events, Unset] = unset,
        filter: typing.Union['IoArgoprojEventsV1alpha1S3Filter', Unset] = unset,
        insecure: typing.Union[insecure, Unset] = unset,
        metadata: typing.Union[metadata, Unset] = unset,
        region: typing.Union[region, Unset] = unset,
        secretKey: typing.Union['SecretKeySelector', Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'IoArgoprojEventsV1alpha1S3Artifact':
        return super().__new__(
            cls,
            *args,
            accessKey=accessKey,
            bucket=bucket,
            endpoint=endpoint,
            events=events,
            filter=filter,
            insecure=insecure,
            metadata=metadata,
            region=region,
            secretKey=secretKey,
            _configuration=_configuration,
            **kwargs,
        )

from argo_workflows.model.io_argoproj_events_v1alpha1_s3_bucket import IoArgoprojEventsV1alpha1S3Bucket
from argo_workflows.model.io_argoproj_events_v1alpha1_s3_filter import IoArgoprojEventsV1alpha1S3Filter
from argo_workflows.model.secret_key_selector import SecretKeySelector
