# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class IoArgoprojEventsV1alpha1CustomTrigger(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    CustomTrigger refers to the specification of the custom trigger.
    """

    @classmethod
    @property
    def certSecret(cls) -> typing.Type['SecretKeySelector']:
        return SecretKeySelector
    
    
    class parameters(
        ListSchema
    ):
    
        @classmethod
        @property
        def _items(cls) -> typing.Type['IoArgoprojEventsV1alpha1TriggerParameter']:
            return IoArgoprojEventsV1alpha1TriggerParameter
    
    
    class payload(
        ListSchema
    ):
    
        @classmethod
        @property
        def _items(cls) -> typing.Type['IoArgoprojEventsV1alpha1TriggerParameter']:
            return IoArgoprojEventsV1alpha1TriggerParameter
    secure = BoolSchema
    serverNameOverride = StrSchema
    serverURL = StrSchema
    
    
    class spec(
        DictSchema
    ):
        _additional_properties = StrSchema
    
    
        def __new__(
            cls,
            *args: typing.Union[dict, frozendict, ],
            _configuration: typing.Optional[Configuration] = None,
            **kwargs: typing.Type[Schema],
        ) -> 'spec':
            return super().__new__(
                cls,
                *args,
                _configuration=_configuration,
                **kwargs,
            )


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        certSecret: typing.Union['SecretKeySelector', Unset] = unset,
        parameters: typing.Union[parameters, Unset] = unset,
        payload: typing.Union[payload, Unset] = unset,
        secure: typing.Union[secure, Unset] = unset,
        serverNameOverride: typing.Union[serverNameOverride, Unset] = unset,
        serverURL: typing.Union[serverURL, Unset] = unset,
        spec: typing.Union[spec, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'IoArgoprojEventsV1alpha1CustomTrigger':
        return super().__new__(
            cls,
            *args,
            certSecret=certSecret,
            parameters=parameters,
            payload=payload,
            secure=secure,
            serverNameOverride=serverNameOverride,
            serverURL=serverURL,
            spec=spec,
            _configuration=_configuration,
            **kwargs,
        )

from argo_workflows.model.io_argoproj_events_v1alpha1_trigger_parameter import IoArgoprojEventsV1alpha1TriggerParameter
from argo_workflows.model.secret_key_selector import SecretKeySelector
