# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class IoArgoprojEventsV1alpha1OpenWhiskTrigger(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    OpenWhiskTrigger refers to the specification of the OpenWhisk trigger.
    """
    actionName = StrSchema

    @classmethod
    @property
    def authToken(cls) -> typing.Type['SecretKeySelector']:
        return SecretKeySelector
    host = StrSchema
    namespace = StrSchema
    
    
    class parameters(
        ListSchema
    ):
    
        @classmethod
        @property
        def _items(cls) -> typing.Type['IoArgoprojEventsV1alpha1TriggerParameter']:
            return IoArgoprojEventsV1alpha1TriggerParameter
    
    
    class payload(
        ListSchema
    ):
    
        @classmethod
        @property
        def _items(cls) -> typing.Type['IoArgoprojEventsV1alpha1TriggerParameter']:
            return IoArgoprojEventsV1alpha1TriggerParameter
    version = StrSchema


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        actionName: typing.Union[actionName, Unset] = unset,
        authToken: typing.Union['SecretKeySelector', Unset] = unset,
        host: typing.Union[host, Unset] = unset,
        namespace: typing.Union[namespace, Unset] = unset,
        parameters: typing.Union[parameters, Unset] = unset,
        payload: typing.Union[payload, Unset] = unset,
        version: typing.Union[version, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'IoArgoprojEventsV1alpha1OpenWhiskTrigger':
        return super().__new__(
            cls,
            *args,
            actionName=actionName,
            authToken=authToken,
            host=host,
            namespace=namespace,
            parameters=parameters,
            payload=payload,
            version=version,
            _configuration=_configuration,
            **kwargs,
        )

from argo_workflows.model.io_argoproj_events_v1alpha1_trigger_parameter import IoArgoprojEventsV1alpha1TriggerParameter
from argo_workflows.model.secret_key_selector import SecretKeySelector
