# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class IoArgoprojWorkflowV1alpha1ContainerSetTemplate(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    _required_property_names = set((
        'containers',
    ))
    
    
    class containers(
        ListSchema
    ):
    
        @classmethod
        @property
        def _items(cls) -> typing.Type['IoArgoprojWorkflowV1alpha1ContainerNode']:
            return IoArgoprojWorkflowV1alpha1ContainerNode

    @classmethod
    @property
    def retryStrategy(cls) -> typing.Type['IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy']:
        return IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy
    
    
    class volumeMounts(
        ListSchema
    ):
    
        @classmethod
        @property
        def _items(cls) -> typing.Type['VolumeMount']:
            return VolumeMount


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        containers: containers,
        retryStrategy: typing.Union['IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy', Unset] = unset,
        volumeMounts: typing.Union[volumeMounts, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'IoArgoprojWorkflowV1alpha1ContainerSetTemplate':
        return super().__new__(
            cls,
            *args,
            containers=containers,
            retryStrategy=retryStrategy,
            volumeMounts=volumeMounts,
            _configuration=_configuration,
            **kwargs,
        )

from argo_workflows.model.io_argoproj_workflow_v1alpha1_container_node import IoArgoprojWorkflowV1alpha1ContainerNode
from argo_workflows.model.io_argoproj_workflow_v1alpha1_container_set_retry_strategy import IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy
from argo_workflows.model.volume_mount import VolumeMount
