# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class IoArgoprojEventsV1alpha1SQSEventSource(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    @classmethod
    @property
    def accessKey(cls) -> typing.Type['SecretKeySelector']:
        return SecretKeySelector
    dlq = BoolSchema
    endpoint = StrSchema

    @classmethod
    @property
    def filter(cls) -> typing.Type['IoArgoprojEventsV1alpha1EventSourceFilter']:
        return IoArgoprojEventsV1alpha1EventSourceFilter
    jsonBody = BoolSchema
    
    
    class metadata(
        DictSchema
    ):
        _additional_properties = StrSchema
    
    
        def __new__(
            cls,
            *args: typing.Union[dict, frozendict, ],
            _configuration: typing.Optional[Configuration] = None,
            **kwargs: typing.Type[Schema],
        ) -> 'metadata':
            return super().__new__(
                cls,
                *args,
                _configuration=_configuration,
                **kwargs,
            )
    queue = StrSchema
    queueAccountId = StrSchema
    region = StrSchema
    roleARN = StrSchema

    @classmethod
    @property
    def secretKey(cls) -> typing.Type['SecretKeySelector']:
        return SecretKeySelector
    waitTimeSeconds = StrSchema


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        accessKey: typing.Union['SecretKeySelector', Unset] = unset,
        dlq: typing.Union[dlq, Unset] = unset,
        endpoint: typing.Union[endpoint, Unset] = unset,
        filter: typing.Union['IoArgoprojEventsV1alpha1EventSourceFilter', Unset] = unset,
        jsonBody: typing.Union[jsonBody, Unset] = unset,
        metadata: typing.Union[metadata, Unset] = unset,
        queue: typing.Union[queue, Unset] = unset,
        queueAccountId: typing.Union[queueAccountId, Unset] = unset,
        region: typing.Union[region, Unset] = unset,
        roleARN: typing.Union[roleARN, Unset] = unset,
        secretKey: typing.Union['SecretKeySelector', Unset] = unset,
        waitTimeSeconds: typing.Union[waitTimeSeconds, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'IoArgoprojEventsV1alpha1SQSEventSource':
        return super().__new__(
            cls,
            *args,
            accessKey=accessKey,
            dlq=dlq,
            endpoint=endpoint,
            filter=filter,
            jsonBody=jsonBody,
            metadata=metadata,
            queue=queue,
            queueAccountId=queueAccountId,
            region=region,
            roleARN=roleARN,
            secretKey=secretKey,
            waitTimeSeconds=waitTimeSeconds,
            _configuration=_configuration,
            **kwargs,
        )

from argo_workflows.model.io_argoproj_events_v1alpha1_event_source_filter import IoArgoprojEventsV1alpha1EventSourceFilter
from argo_workflows.model.secret_key_selector import SecretKeySelector
