# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class IoArgoprojWorkflowV1alpha1ValueFrom(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    ValueFrom describes a location in which to obtain the value to a parameter
    """

    @classmethod
    @property
    def configMapKeyRef(cls) -> typing.Type['ConfigMapKeySelector']:
        return ConfigMapKeySelector
    default = StrSchema
    event = StrSchema
    expression = StrSchema
    jqFilter = StrSchema
    jsonPath = StrSchema
    parameter = StrSchema
    path = StrSchema
    supplied = DictSchema


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        configMapKeyRef: typing.Union['ConfigMapKeySelector', Unset] = unset,
        default: typing.Union[default, Unset] = unset,
        event: typing.Union[event, Unset] = unset,
        expression: typing.Union[expression, Unset] = unset,
        jqFilter: typing.Union[jqFilter, Unset] = unset,
        jsonPath: typing.Union[jsonPath, Unset] = unset,
        parameter: typing.Union[parameter, Unset] = unset,
        path: typing.Union[path, Unset] = unset,
        supplied: typing.Union[supplied, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'IoArgoprojWorkflowV1alpha1ValueFrom':
        return super().__new__(
            cls,
            *args,
            configMapKeyRef=configMapKeyRef,
            default=default,
            event=event,
            expression=expression,
            jqFilter=jqFilter,
            jsonPath=jsonPath,
            parameter=parameter,
            path=path,
            supplied=supplied,
            _configuration=_configuration,
            **kwargs,
        )

from argo_workflows.model.config_map_key_selector import ConfigMapKeySelector
