# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class IoArgoprojEventsV1alpha1PulsarEventSource(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    @classmethod
    @property
    def authTokenSecret(cls) -> typing.Type['SecretKeySelector']:
        return SecretKeySelector

    @classmethod
    @property
    def connectionBackoff(cls) -> typing.Type['IoArgoprojEventsV1alpha1Backoff']:
        return IoArgoprojEventsV1alpha1Backoff

    @classmethod
    @property
    def filter(cls) -> typing.Type['IoArgoprojEventsV1alpha1EventSourceFilter']:
        return IoArgoprojEventsV1alpha1EventSourceFilter
    jsonBody = BoolSchema
    
    
    class metadata(
        DictSchema
    ):
        _additional_properties = StrSchema
    
    
        def __new__(
            cls,
            *args: typing.Union[dict, frozendict, ],
            _configuration: typing.Optional[Configuration] = None,
            **kwargs: typing.Type[Schema],
        ) -> 'metadata':
            return super().__new__(
                cls,
                *args,
                _configuration=_configuration,
                **kwargs,
            )

    @classmethod
    @property
    def tls(cls) -> typing.Type['IoArgoprojEventsV1alpha1TLSConfig']:
        return IoArgoprojEventsV1alpha1TLSConfig
    tlsAllowInsecureConnection = BoolSchema

    @classmethod
    @property
    def tlsTrustCertsSecret(cls) -> typing.Type['SecretKeySelector']:
        return SecretKeySelector
    tlsValidateHostname = BoolSchema
    
    
    class topics(
        ListSchema
    ):
        _items = StrSchema
    type = StrSchema
    url = StrSchema


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        authTokenSecret: typing.Union['SecretKeySelector', Unset] = unset,
        connectionBackoff: typing.Union['IoArgoprojEventsV1alpha1Backoff', Unset] = unset,
        filter: typing.Union['IoArgoprojEventsV1alpha1EventSourceFilter', Unset] = unset,
        jsonBody: typing.Union[jsonBody, Unset] = unset,
        metadata: typing.Union[metadata, Unset] = unset,
        tls: typing.Union['IoArgoprojEventsV1alpha1TLSConfig', Unset] = unset,
        tlsAllowInsecureConnection: typing.Union[tlsAllowInsecureConnection, Unset] = unset,
        tlsTrustCertsSecret: typing.Union['SecretKeySelector', Unset] = unset,
        tlsValidateHostname: typing.Union[tlsValidateHostname, Unset] = unset,
        topics: typing.Union[topics, Unset] = unset,
        type: typing.Union[type, Unset] = unset,
        url: typing.Union[url, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'IoArgoprojEventsV1alpha1PulsarEventSource':
        return super().__new__(
            cls,
            *args,
            authTokenSecret=authTokenSecret,
            connectionBackoff=connectionBackoff,
            filter=filter,
            jsonBody=jsonBody,
            metadata=metadata,
            tls=tls,
            tlsAllowInsecureConnection=tlsAllowInsecureConnection,
            tlsTrustCertsSecret=tlsTrustCertsSecret,
            tlsValidateHostname=tlsValidateHostname,
            topics=topics,
            type=type,
            url=url,
            _configuration=_configuration,
            **kwargs,
        )

from argo_workflows.model.io_argoproj_events_v1alpha1_backoff import IoArgoprojEventsV1alpha1Backoff
from argo_workflows.model.io_argoproj_events_v1alpha1_event_source_filter import IoArgoprojEventsV1alpha1EventSourceFilter
from argo_workflows.model.io_argoproj_events_v1alpha1_tls_config import IoArgoprojEventsV1alpha1TLSConfig
from argo_workflows.model.secret_key_selector import SecretKeySelector
