# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class ISCSIVolumeSource(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Represents an ISCSI disk. ISCSI volumes can only be mounted as read/write once. ISCSI volumes support ownership management and SELinux relabeling.
    """
    _required_property_names = set((
        'iqn',
        'lun',
        'targetPortal',
    ))
    chapAuthDiscovery = BoolSchema
    chapAuthSession = BoolSchema
    fsType = StrSchema
    initiatorName = StrSchema
    iqn = StrSchema
    iscsiInterface = StrSchema
    lun = IntSchema
    
    
    class portals(
        ListSchema
    ):
        _items = StrSchema
    readOnly = BoolSchema

    @classmethod
    @property
    def secretRef(cls) -> typing.Type['LocalObjectReference']:
        return LocalObjectReference
    targetPortal = StrSchema


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        iqn: iqn,
        lun: lun,
        targetPortal: targetPortal,
        chapAuthDiscovery: typing.Union[chapAuthDiscovery, Unset] = unset,
        chapAuthSession: typing.Union[chapAuthSession, Unset] = unset,
        fsType: typing.Union[fsType, Unset] = unset,
        initiatorName: typing.Union[initiatorName, Unset] = unset,
        iscsiInterface: typing.Union[iscsiInterface, Unset] = unset,
        portals: typing.Union[portals, Unset] = unset,
        readOnly: typing.Union[readOnly, Unset] = unset,
        secretRef: typing.Union['LocalObjectReference', Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'ISCSIVolumeSource':
        return super().__new__(
            cls,
            *args,
            iqn=iqn,
            lun=lun,
            targetPortal=targetPortal,
            chapAuthDiscovery=chapAuthDiscovery,
            chapAuthSession=chapAuthSession,
            fsType=fsType,
            initiatorName=initiatorName,
            iscsiInterface=iscsiInterface,
            portals=portals,
            readOnly=readOnly,
            secretRef=secretRef,
            _configuration=_configuration,
            **kwargs,
        )

from argo_workflows.model.local_object_reference import LocalObjectReference
