# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class ManagedFieldsEntry(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    ManagedFieldsEntry is a workflow-id, a FieldSet and the group version of the resource that the fieldset applies to.
    """
    apiVersion = StrSchema
    fieldsType = StrSchema
    fieldsV1 = DictSchema
    manager = StrSchema
    operation = StrSchema
    subresource = StrSchema
    time = DateTimeSchema


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        apiVersion: typing.Union[apiVersion, Unset] = unset,
        fieldsType: typing.Union[fieldsType, Unset] = unset,
        fieldsV1: typing.Union[fieldsV1, Unset] = unset,
        manager: typing.Union[manager, Unset] = unset,
        operation: typing.Union[operation, Unset] = unset,
        subresource: typing.Union[subresource, Unset] = unset,
        time: typing.Union[time, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'ManagedFieldsEntry':
        return super().__new__(
            cls,
            *args,
            apiVersion=apiVersion,
            fieldsType=fieldsType,
            fieldsV1=fieldsV1,
            manager=manager,
            operation=operation,
            subresource=subresource,
            time=time,
            _configuration=_configuration,
            **kwargs,
        )
