# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class OwnerReference(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    OwnerReference contains enough information to let you identify an owning object. An owning object must be in the same namespace as the dependent, or be cluster-scoped, so there is no namespace field.
    """
    _required_property_names = set((
        'apiVersion',
        'kind',
        'name',
        'uid',
    ))
    apiVersion = StrSchema
    blockOwnerDeletion = BoolSchema
    controller = BoolSchema
    kind = StrSchema
    name = StrSchema
    uid = StrSchema


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        apiVersion: apiVersion,
        kind: kind,
        name: name,
        uid: uid,
        blockOwnerDeletion: typing.Union[blockOwnerDeletion, Unset] = unset,
        controller: typing.Union[controller, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'OwnerReference':
        return super().__new__(
            cls,
            *args,
            apiVersion=apiVersion,
            kind=kind,
            name=name,
            uid=uid,
            blockOwnerDeletion=blockOwnerDeletion,
            controller=controller,
            _configuration=_configuration,
            **kwargs,
        )
