# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class PersistentVolumeClaim(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    PersistentVolumeClaim is a user's request for and claim to a persistent volume
    """
    apiVersion = StrSchema
    kind = StrSchema

    @classmethod
    @property
    def metadata(cls) -> typing.Type['ObjectMeta']:
        return ObjectMeta

    @classmethod
    @property
    def spec(cls) -> typing.Type['PersistentVolumeClaimSpec']:
        return PersistentVolumeClaimSpec

    @classmethod
    @property
    def status(cls) -> typing.Type['PersistentVolumeClaimStatus']:
        return PersistentVolumeClaimStatus


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        apiVersion: typing.Union[apiVersion, Unset] = unset,
        kind: typing.Union[kind, Unset] = unset,
        metadata: typing.Union['ObjectMeta', Unset] = unset,
        spec: typing.Union['PersistentVolumeClaimSpec', Unset] = unset,
        status: typing.Union['PersistentVolumeClaimStatus', Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'PersistentVolumeClaim':
        return super().__new__(
            cls,
            *args,
            apiVersion=apiVersion,
            kind=kind,
            metadata=metadata,
            spec=spec,
            status=status,
            _configuration=_configuration,
            **kwargs,
        )

from argo_workflows.model.object_meta import ObjectMeta
from argo_workflows.model.persistent_volume_claim_spec import PersistentVolumeClaimSpec
from argo_workflows.model.persistent_volume_claim_status import PersistentVolumeClaimStatus
