# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class ScaleIOVolumeSource(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    ScaleIOVolumeSource represents a persistent ScaleIO volume
    """
    _required_property_names = set((
        'gateway',
        'secretRef',
        'system',
    ))
    fsType = StrSchema
    gateway = StrSchema
    protectionDomain = StrSchema
    readOnly = BoolSchema

    @classmethod
    @property
    def secretRef(cls) -> typing.Type['LocalObjectReference']:
        return LocalObjectReference
    sslEnabled = BoolSchema
    storageMode = StrSchema
    storagePool = StrSchema
    system = StrSchema
    volumeName = StrSchema


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        gateway: gateway,
        secretRef: secretRef,
        system: system,
        fsType: typing.Union[fsType, Unset] = unset,
        protectionDomain: typing.Union[protectionDomain, Unset] = unset,
        readOnly: typing.Union[readOnly, Unset] = unset,
        sslEnabled: typing.Union[sslEnabled, Unset] = unset,
        storageMode: typing.Union[storageMode, Unset] = unset,
        storagePool: typing.Union[storagePool, Unset] = unset,
        volumeName: typing.Union[volumeName, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'ScaleIOVolumeSource':
        return super().__new__(
            cls,
            *args,
            gateway=gateway,
            secretRef=secretRef,
            system=system,
            fsType=fsType,
            protectionDomain=protectionDomain,
            readOnly=readOnly,
            sslEnabled=sslEnabled,
            storageMode=storageMode,
            storagePool=storagePool,
            volumeName=volumeName,
            _configuration=_configuration,
            **kwargs,
        )

from argo_workflows.model.local_object_reference import LocalObjectReference
