# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class VolumeProjection(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Projection that may be projected along with other supported volume types
    """

    @classmethod
    @property
    def configMap(cls) -> typing.Type['ConfigMapProjection']:
        return ConfigMapProjection

    @classmethod
    @property
    def downwardAPI(cls) -> typing.Type['DownwardAPIProjection']:
        return DownwardAPIProjection

    @classmethod
    @property
    def secret(cls) -> typing.Type['SecretProjection']:
        return SecretProjection

    @classmethod
    @property
    def serviceAccountToken(cls) -> typing.Type['ServiceAccountTokenProjection']:
        return ServiceAccountTokenProjection


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        configMap: typing.Union['ConfigMapProjection', Unset] = unset,
        downwardAPI: typing.Union['DownwardAPIProjection', Unset] = unset,
        secret: typing.Union['SecretProjection', Unset] = unset,
        serviceAccountToken: typing.Union['ServiceAccountTokenProjection', Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'VolumeProjection':
        return super().__new__(
            cls,
            *args,
            configMap=configMap,
            downwardAPI=downwardAPI,
            secret=secret,
            serviceAccountToken=serviceAccountToken,
            _configuration=_configuration,
            **kwargs,
        )

from argo_workflows.model.config_map_projection import ConfigMapProjection
from argo_workflows.model.downward_api_projection import DownwardAPIProjection
from argo_workflows.model.secret_projection import SecretProjection
from argo_workflows.model.service_account_token_projection import ServiceAccountTokenProjection
