# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

from dataclasses import dataclass
import re  # noqa: F401
import sys  # noqa: F401
import typing
import urllib3
import functools  # noqa: F401
from urllib3._collections import HTTPHeaderDict

from argo_workflows import api_client, exceptions
import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from argo_workflows.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)

from argo_workflows.model.grpc_gateway_runtime_error import GrpcGatewayRuntimeError
from argo_workflows.model.eventsource_log_entry import EventsourceLogEntry
from argo_workflows.model.grpc_gateway_runtime_stream_error import GrpcGatewayRuntimeStreamError

# query params
NameSchema = StrSchema
EventSourceTypeSchema = StrSchema
EventNameSchema = StrSchema
GrepSchema = StrSchema
PodLogOptionsContainerSchema = StrSchema
PodLogOptionsFollowSchema = BoolSchema
PodLogOptionsPreviousSchema = BoolSchema
PodLogOptionsSinceSecondsSchema = StrSchema
PodLogOptionsSinceTimeSecondsSchema = StrSchema
PodLogOptionsSinceTimeNanosSchema = Int32Schema
PodLogOptionsTimestampsSchema = BoolSchema
PodLogOptionsTailLinesSchema = StrSchema
PodLogOptionsLimitBytesSchema = StrSchema
PodLogOptionsInsecureSkipTLSVerifyBackendSchema = BoolSchema
RequestRequiredQueryParams = typing.TypedDict(
    'RequestRequiredQueryParams',
    {
    }
)
RequestOptionalQueryParams = typing.TypedDict(
    'RequestOptionalQueryParams',
    {
        'name': NameSchema,
        'eventSourceType': EventSourceTypeSchema,
        'eventName': EventNameSchema,
        'grep': GrepSchema,
        'podLogOptions.container': PodLogOptionsContainerSchema,
        'podLogOptions.follow': PodLogOptionsFollowSchema,
        'podLogOptions.previous': PodLogOptionsPreviousSchema,
        'podLogOptions.sinceSeconds': PodLogOptionsSinceSecondsSchema,
        'podLogOptions.sinceTime.seconds': PodLogOptionsSinceTimeSecondsSchema,
        'podLogOptions.sinceTime.nanos': PodLogOptionsSinceTimeNanosSchema,
        'podLogOptions.timestamps': PodLogOptionsTimestampsSchema,
        'podLogOptions.tailLines': PodLogOptionsTailLinesSchema,
        'podLogOptions.limitBytes': PodLogOptionsLimitBytesSchema,
        'podLogOptions.insecureSkipTLSVerifyBackend': PodLogOptionsInsecureSkipTLSVerifyBackendSchema,
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_name = api_client.QueryParameter(
    name="name",
    schema=NameSchema,
)
request_query_event_source_type = api_client.QueryParameter(
    name="eventSourceType",
    schema=EventSourceTypeSchema,
)
request_query_event_name = api_client.QueryParameter(
    name="eventName",
    schema=EventNameSchema,
)
request_query_grep = api_client.QueryParameter(
    name="grep",
    schema=GrepSchema,
)
request_query_pod_log_options_container = api_client.QueryParameter(
    name="podLogOptions.container",
    schema=PodLogOptionsContainerSchema,
)
request_query_pod_log_options_follow = api_client.QueryParameter(
    name="podLogOptions.follow",
    schema=PodLogOptionsFollowSchema,
)
request_query_pod_log_options_previous = api_client.QueryParameter(
    name="podLogOptions.previous",
    schema=PodLogOptionsPreviousSchema,
)
request_query_pod_log_options_since_seconds = api_client.QueryParameter(
    name="podLogOptions.sinceSeconds",
    schema=PodLogOptionsSinceSecondsSchema,
)
request_query_pod_log_options_since_time_seconds = api_client.QueryParameter(
    name="podLogOptions.sinceTime.seconds",
    schema=PodLogOptionsSinceTimeSecondsSchema,
)
request_query_pod_log_options_since_time_nanos = api_client.QueryParameter(
    name="podLogOptions.sinceTime.nanos",
    schema=PodLogOptionsSinceTimeNanosSchema,
)
request_query_pod_log_options_timestamps = api_client.QueryParameter(
    name="podLogOptions.timestamps",
    schema=PodLogOptionsTimestampsSchema,
)
request_query_pod_log_options_tail_lines = api_client.QueryParameter(
    name="podLogOptions.tailLines",
    schema=PodLogOptionsTailLinesSchema,
)
request_query_pod_log_options_limit_bytes = api_client.QueryParameter(
    name="podLogOptions.limitBytes",
    schema=PodLogOptionsLimitBytesSchema,
)
request_query_pod_log_options_insecure_skip_tls_verify_backend = api_client.QueryParameter(
    name="podLogOptions.insecureSkipTLSVerifyBackend",
    schema=PodLogOptionsInsecureSkipTLSVerifyBackendSchema,
)
# path params
NamespaceSchema = StrSchema
RequestRequiredPathParams = typing.TypedDict(
    'RequestRequiredPathParams',
    {
        'namespace': NamespaceSchema,
    }
)
RequestOptionalPathParams = typing.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_namespace = api_client.PathParameter(
    name="namespace",
    schema=NamespaceSchema,
    required=True,
)
_path = '/api/v1/stream/event-sources/{namespace}/logs'
_method = 'GET'
_auth = [
    'BearerToken',
]


class SchemaFor200ResponseBodyApplicationJson(
    DictSchema
):

    @classmethod
    @property
    def error(cls) -> typing.Type['GrpcGatewayRuntimeStreamError']:
        return GrpcGatewayRuntimeStreamError

    @classmethod
    @property
    def result(cls) -> typing.Type['EventsourceLogEntry']:
        return EventsourceLogEntry


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        error: typing.Union['GrpcGatewayRuntimeStreamError', Unset] = unset,
        result: typing.Union['EventsourceLogEntry', Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'SchemaFor200ResponseBodyApplicationJson':
        return super().__new__(
            cls,
            *args,
            error=error,
            result=result,
            _configuration=_configuration,
            **kwargs,
        )


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    response: urllib3.HTTPResponse
    body: typing.Union[
        SchemaFor200ResponseBodyApplicationJson,
    ]
    headers: Unset = unset


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
SchemaFor0ResponseBodyApplicationJson = GrpcGatewayRuntimeError


@dataclass
class ApiResponseForDefault(api_client.ApiResponse):
    response: urllib3.HTTPResponse
    body: typing.Union[
        SchemaFor0ResponseBodyApplicationJson,
    ]
    headers: Unset = unset


_response_for_default = api_client.OpenApiResponse(
    response_cls=ApiResponseForDefault,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor0ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
    'default': _response_for_default,
}
_all_accept_content_types = (
    'application/json',
)


class EventSourcesLogs(api_client.Api):

    def event_sources_logs(
        self: api_client.Api,
        query_params: RequestQueryParams = frozendict(),
        path_params: RequestPathParams = frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
        skip_deserialization: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization
    ]:
        """
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs(RequestPathParams, path_params)

        _path_params = {}
        for parameter in (
            request_path_namespace,
        ):
            parameter_data = path_params.get(parameter.name, unset)
            if parameter_data is unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)

        _query_params = []
        for parameter in (
            request_query_name,
            request_query_event_source_type,
            request_query_event_name,
            request_query_grep,
            request_query_pod_log_options_container,
            request_query_pod_log_options_follow,
            request_query_pod_log_options_previous,
            request_query_pod_log_options_since_seconds,
            request_query_pod_log_options_since_time_seconds,
            request_query_pod_log_options_since_time_nanos,
            request_query_pod_log_options_timestamps,
            request_query_pod_log_options_tail_lines,
            request_query_pod_log_options_limit_bytes,
            request_query_pod_log_options_insecure_skip_tls_verify_backend,
        ):
            parameter_data = query_params.get(parameter.name, unset)
            if parameter_data is unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _query_params.extend(serialized_data)

        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)

        response = self.api_client.call_api(
            resource_path=_path,
            method=_method,
            path_params=_path_params,
            query_params=tuple(_query_params),
            headers=_headers,
            auth_settings=_auth,
            stream=stream,
            timeout=timeout,
        )

        if skip_deserialization:
            api_response = api_client.ApiResponseWithoutDeserialization(response=response)
        else:
            response_for_status = _status_code_to_response.get(str(response.status))
            if response_for_status:
                api_response = response_for_status.deserialize(response, self.api_client.configuration)
            else:
                default_response = _status_code_to_response.get('default')
                if default_response:
                    api_response = default_response.deserialize(response, self.api_client.configuration)
                else:
                    api_response = api_client.ApiResponseWithoutDeserialization(response=response)

        if not 200 <= response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)

        return api_response
